<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>com.forwardmeasure.objectstorage</groupId><artifactId>forwardmeasure-object-storage-parent</artifactId><version>${revision}</version></parent>
  <artifactId>forwardmeasure-object-storage-api</artifactId>
  <name>ForwardMeasure Object Storage API</name>
  <dependencies>
    <dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId></dependency>
  </dependencies>
</project>

