<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>com.forwardmeasure.objectstorage</groupId><artifactId>forwardmeasure-object-storage-parent</artifactId><version>${revision}</version></parent>
  <artifactId>forwardmeasure-object-storage-azure</artifactId>
  <name>ForwardMeasure Object Storage Azure</name>
  <dependencies>
    <dependency><groupId>${project.groupId}</groupId><artifactId>forwardmeasure-object-storage-core</artifactId></dependency>
    <dependency><groupId>com.azure</groupId><artifactId>azure-storage-blob</artifactId></dependency>
    <dependency><groupId>com.azure</groupId><artifactId>azure-core-http-netty</artifactId></dependency>
    <dependency><groupId>org.testcontainers</groupId><artifactId>testcontainers</artifactId><scope>test</scope></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
